// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package queries

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/Khan/genqlient/graphql"
)

// CatchAllImplementationsRandomItemArticle includes the requested fields of the GraphQL type Article.
type CatchAllImplementationsRandomItemArticle struct {
	Typename string `json:"__typename"`
	// ID is the identifier of the content.
	Id   string `json:"id"`
	Name string `json:"name"`
	Text string `json:"text"`
}

// GetTypename returns CatchAllImplementationsRandomItemArticle.Typename, and is useful for accessing the field via an interface.
func (v *CatchAllImplementationsRandomItemArticle) GetTypename() string { return v.Typename }

// GetId returns CatchAllImplementationsRandomItemArticle.Id, and is useful for accessing the field via an interface.
func (v *CatchAllImplementationsRandomItemArticle) GetId() string { return v.Id }

// GetName returns CatchAllImplementationsRandomItemArticle.Name, and is useful for accessing the field via an interface.
func (v *CatchAllImplementationsRandomItemArticle) GetName() string { return v.Name }

// GetText returns CatchAllImplementationsRandomItemArticle.Text, and is useful for accessing the field via an interface.
func (v *CatchAllImplementationsRandomItemArticle) GetText() string { return v.Text }

// CatchAllImplementationsRandomItemContent includes the requested fields of the GraphQL interface Content.
//
// CatchAllImplementationsRandomItemContent is implemented by the following types:
// CatchAllImplementationsRandomItemArticle
// CatchAllImplementationsRandomItemContentOther
// The GraphQL type's documentation follows.
//
// Content is implemented by various types like Article, Video, and Topic.
type CatchAllImplementationsRandomItemContent interface {
	implementsGraphQLInterfaceCatchAllImplementationsRandomItemContent()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
	// GetId returns the interface-field "id" from its implementation.
	// The GraphQL interface field's documentation follows.
	//
	// ID is the identifier of the content.
	GetId() string
	// GetName returns the interface-field "name" from its implementation.
	GetName() string
}

func (v *CatchAllImplementationsRandomItemArticle) implementsGraphQLInterfaceCatchAllImplementationsRandomItemContent() {
}
func (v *CatchAllImplementationsRandomItemContentOther) implementsGraphQLInterfaceCatchAllImplementationsRandomItemContent() {
}

func __unmarshalCatchAllImplementationsRandomItemContent(b []byte, v *CatchAllImplementationsRandomItemContent) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "Article":
		*v = new(CatchAllImplementationsRandomItemArticle)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing Content.__typename")
	default:
		*v = new(CatchAllImplementationsRandomItemContentOther)
		return json.Unmarshal(b, *v)
	}
}

func __marshalCatchAllImplementationsRandomItemContent(v *CatchAllImplementationsRandomItemContent) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *CatchAllImplementationsRandomItemArticle:
		typename = "Article"

		result := struct {
			TypeName string `json:"__typename"`
			*CatchAllImplementationsRandomItemArticle
		}{typename, v}
		return json.Marshal(result)
	case *CatchAllImplementationsRandomItemContentOther:
		return json.Marshal(v)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for CatchAllImplementationsRandomItemContent: "%T"`, v)
	}
}

// CatchAllImplementationsRandomItemContentOther is the catch-all type used by CatchAllImplementationsRandomItemContent for any concrete
// GraphQL type returned by the server that doesn't have its own
// generated struct (because no fragment selected it). It carries
// only the interface's shared fields; the concrete GraphQL type
// name is available via the __typename field.
type CatchAllImplementationsRandomItemContentOther struct {
	Typename string `json:"__typename"`
	// ID is the identifier of the content.
	Id   string `json:"id"`
	Name string `json:"name"`
}

// GetTypename returns CatchAllImplementationsRandomItemContentOther.Typename, and is useful for accessing the field via an interface.
func (v *CatchAllImplementationsRandomItemContentOther) GetTypename() string { return v.Typename }

// GetId returns CatchAllImplementationsRandomItemContentOther.Id, and is useful for accessing the field via an interface.
func (v *CatchAllImplementationsRandomItemContentOther) GetId() string { return v.Id }

// GetName returns CatchAllImplementationsRandomItemContentOther.Name, and is useful for accessing the field via an interface.
func (v *CatchAllImplementationsRandomItemContentOther) GetName() string { return v.Name }

// CatchAllImplementationsResponse is returned by CatchAllImplementations on success.
type CatchAllImplementationsResponse struct {
	RandomItem CatchAllImplementationsRandomItemContent `json:"-"`
}

// GetRandomItem returns CatchAllImplementationsResponse.RandomItem, and is useful for accessing the field via an interface.
func (v *CatchAllImplementationsResponse) GetRandomItem() CatchAllImplementationsRandomItemContent {
	return v.RandomItem
}

func (v *CatchAllImplementationsResponse) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*CatchAllImplementationsResponse
		RandomItem json.RawMessage `json:"randomItem"`
		graphql.NoUnmarshalJSON
	}
	firstPass.CatchAllImplementationsResponse = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.RandomItem
		src := firstPass.RandomItem
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalCatchAllImplementationsRandomItemContent(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal CatchAllImplementationsResponse.RandomItem: %w", err)
			}
		}
	}
	return nil
}

type __premarshalCatchAllImplementationsResponse struct {
	RandomItem json.RawMessage `json:"randomItem"`
}

func (v *CatchAllImplementationsResponse) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *CatchAllImplementationsResponse) __premarshalJSON() (*__premarshalCatchAllImplementationsResponse, error) {
	var retval __premarshalCatchAllImplementationsResponse

	{

		dst := &retval.RandomItem
		src := v.RandomItem
		var err error
		*dst, err = __marshalCatchAllImplementationsRandomItemContent(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal CatchAllImplementationsResponse.RandomItem: %w", err)
		}
	}
	return &retval, nil
}

// The query executed by CatchAllImplementations.
const CatchAllImplementations_Operation = `
query CatchAllImplementations {
	randomItem {
		__typename
		id
		name
		... on Article {
			text
		}
	}
}
`

func CatchAllImplementations(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *CatchAllImplementationsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CatchAllImplementations",
		Query:  CatchAllImplementations_Operation,
	}

	data_ = &CatchAllImplementationsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

