// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package queries

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/Khan/genqlient/graphql"
)

// InterfaceNoFragmentsQueryRandomItemContent includes the requested fields of the GraphQL interface Content.
//
// InterfaceNoFragmentsQueryRandomItemContent is implemented by the following types:
// InterfaceNoFragmentsQueryRandomItemContentOther
// The GraphQL type's documentation follows.
//
// Content is implemented by various types like Article, Video, and Topic.
type InterfaceNoFragmentsQueryRandomItemContent interface {
	implementsGraphQLInterfaceInterfaceNoFragmentsQueryRandomItemContent()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
	// GetId returns the interface-field "id" from its implementation.
	// The GraphQL interface field's documentation follows.
	//
	// ID is the identifier of the content.
	GetId() string
	// GetName returns the interface-field "name" from its implementation.
	GetName() string
}

func (v *InterfaceNoFragmentsQueryRandomItemContentOther) implementsGraphQLInterfaceInterfaceNoFragmentsQueryRandomItemContent() {
}

func __unmarshalInterfaceNoFragmentsQueryRandomItemContent(b []byte, v *InterfaceNoFragmentsQueryRandomItemContent) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "":
		return fmt.Errorf(
			"response was missing Content.__typename")
	default:
		*v = new(InterfaceNoFragmentsQueryRandomItemContentOther)
		return json.Unmarshal(b, *v)
	}
}

func __marshalInterfaceNoFragmentsQueryRandomItemContent(v *InterfaceNoFragmentsQueryRandomItemContent) ([]byte, error) {

	switch v := (*v).(type) {
	case *InterfaceNoFragmentsQueryRandomItemContentOther:
		return json.Marshal(v)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for InterfaceNoFragmentsQueryRandomItemContent: "%T"`, v)
	}
}

// InterfaceNoFragmentsQueryRandomItemContentOther is the catch-all for InterfaceNoFragmentsQueryRandomItemContent implementations that aren't explicitly fragmented; the concrete type-name is in __typename.
type InterfaceNoFragmentsQueryRandomItemContentOther struct {
	Typename string `json:"__typename"`
	// ID is the identifier of the content.
	Id   string `json:"id"`
	Name string `json:"name"`
}

// GetTypename returns InterfaceNoFragmentsQueryRandomItemContentOther.Typename, and is useful for accessing the field via an interface.
func (v *InterfaceNoFragmentsQueryRandomItemContentOther) GetTypename() string { return v.Typename }

// GetId returns InterfaceNoFragmentsQueryRandomItemContentOther.Id, and is useful for accessing the field via an interface.
func (v *InterfaceNoFragmentsQueryRandomItemContentOther) GetId() string { return v.Id }

// GetName returns InterfaceNoFragmentsQueryRandomItemContentOther.Name, and is useful for accessing the field via an interface.
func (v *InterfaceNoFragmentsQueryRandomItemContentOther) GetName() string { return v.Name }

// InterfaceNoFragmentsQueryRandomItemWithTypeNameContent includes the requested fields of the GraphQL interface Content.
//
// InterfaceNoFragmentsQueryRandomItemWithTypeNameContent is implemented by the following types:
// InterfaceNoFragmentsQueryRandomItemWithTypeNameContentOther
// The GraphQL type's documentation follows.
//
// Content is implemented by various types like Article, Video, and Topic.
type InterfaceNoFragmentsQueryRandomItemWithTypeNameContent interface {
	implementsGraphQLInterfaceInterfaceNoFragmentsQueryRandomItemWithTypeNameContent()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
	// GetId returns the interface-field "id" from its implementation.
	// The GraphQL interface field's documentation follows.
	//
	// ID is the identifier of the content.
	GetId() string
	// GetName returns the interface-field "name" from its implementation.
	GetName() string
}

func (v *InterfaceNoFragmentsQueryRandomItemWithTypeNameContentOther) implementsGraphQLInterfaceInterfaceNoFragmentsQueryRandomItemWithTypeNameContent() {
}

func __unmarshalInterfaceNoFragmentsQueryRandomItemWithTypeNameContent(b []byte, v *InterfaceNoFragmentsQueryRandomItemWithTypeNameContent) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "":
		return fmt.Errorf(
			"response was missing Content.__typename")
	default:
		*v = new(InterfaceNoFragmentsQueryRandomItemWithTypeNameContentOther)
		return json.Unmarshal(b, *v)
	}
}

func __marshalInterfaceNoFragmentsQueryRandomItemWithTypeNameContent(v *InterfaceNoFragmentsQueryRandomItemWithTypeNameContent) ([]byte, error) {

	switch v := (*v).(type) {
	case *InterfaceNoFragmentsQueryRandomItemWithTypeNameContentOther:
		return json.Marshal(v)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for InterfaceNoFragmentsQueryRandomItemWithTypeNameContent: "%T"`, v)
	}
}

// InterfaceNoFragmentsQueryRandomItemWithTypeNameContentOther is the catch-all for InterfaceNoFragmentsQueryRandomItemWithTypeNameContent implementations that aren't explicitly fragmented; the concrete type-name is in __typename.
type InterfaceNoFragmentsQueryRandomItemWithTypeNameContentOther struct {
	Typename string `json:"__typename"`
	// ID is the identifier of the content.
	Id   string `json:"id"`
	Name string `json:"name"`
}

// GetTypename returns InterfaceNoFragmentsQueryRandomItemWithTypeNameContentOther.Typename, and is useful for accessing the field via an interface.
func (v *InterfaceNoFragmentsQueryRandomItemWithTypeNameContentOther) GetTypename() string {
	return v.Typename
}

// GetId returns InterfaceNoFragmentsQueryRandomItemWithTypeNameContentOther.Id, and is useful for accessing the field via an interface.
func (v *InterfaceNoFragmentsQueryRandomItemWithTypeNameContentOther) GetId() string { return v.Id }

// GetName returns InterfaceNoFragmentsQueryRandomItemWithTypeNameContentOther.Name, and is useful for accessing the field via an interface.
func (v *InterfaceNoFragmentsQueryRandomItemWithTypeNameContentOther) GetName() string { return v.Name }

// InterfaceNoFragmentsQueryResponse is returned by InterfaceNoFragmentsQuery on success.
type InterfaceNoFragmentsQueryResponse struct {
	Root                   InterfaceNoFragmentsQueryRootTopic                     `json:"root"`
	RandomItem             InterfaceNoFragmentsQueryRandomItemContent             `json:"-"`
	RandomItemWithTypeName InterfaceNoFragmentsQueryRandomItemWithTypeNameContent `json:"-"`
	WithPointer            *InterfaceNoFragmentsQueryWithPointerContent           `json:"-"`
}

// GetRoot returns InterfaceNoFragmentsQueryResponse.Root, and is useful for accessing the field via an interface.
func (v *InterfaceNoFragmentsQueryResponse) GetRoot() InterfaceNoFragmentsQueryRootTopic {
	return v.Root
}

// GetRandomItem returns InterfaceNoFragmentsQueryResponse.RandomItem, and is useful for accessing the field via an interface.
func (v *InterfaceNoFragmentsQueryResponse) GetRandomItem() InterfaceNoFragmentsQueryRandomItemContent {
	return v.RandomItem
}

// GetRandomItemWithTypeName returns InterfaceNoFragmentsQueryResponse.RandomItemWithTypeName, and is useful for accessing the field via an interface.
func (v *InterfaceNoFragmentsQueryResponse) GetRandomItemWithTypeName() InterfaceNoFragmentsQueryRandomItemWithTypeNameContent {
	return v.RandomItemWithTypeName
}

// GetWithPointer returns InterfaceNoFragmentsQueryResponse.WithPointer, and is useful for accessing the field via an interface.
func (v *InterfaceNoFragmentsQueryResponse) GetWithPointer() *InterfaceNoFragmentsQueryWithPointerContent {
	return v.WithPointer
}

func (v *InterfaceNoFragmentsQueryResponse) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*InterfaceNoFragmentsQueryResponse
		RandomItem             json.RawMessage `json:"randomItem"`
		RandomItemWithTypeName json.RawMessage `json:"randomItemWithTypeName"`
		WithPointer            json.RawMessage `json:"withPointer"`
		graphql.NoUnmarshalJSON
	}
	firstPass.InterfaceNoFragmentsQueryResponse = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.RandomItem
		src := firstPass.RandomItem
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalInterfaceNoFragmentsQueryRandomItemContent(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal InterfaceNoFragmentsQueryResponse.RandomItem: %w", err)
			}
		}
	}

	{
		dst := &v.RandomItemWithTypeName
		src := firstPass.RandomItemWithTypeName
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalInterfaceNoFragmentsQueryRandomItemWithTypeNameContent(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal InterfaceNoFragmentsQueryResponse.RandomItemWithTypeName: %w", err)
			}
		}
	}

	{
		dst := &v.WithPointer
		src := firstPass.WithPointer
		if len(src) != 0 && string(src) != "null" {
			*dst = new(InterfaceNoFragmentsQueryWithPointerContent)
			err = __unmarshalInterfaceNoFragmentsQueryWithPointerContent(
				src, *dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal InterfaceNoFragmentsQueryResponse.WithPointer: %w", err)
			}
		}
	}
	return nil
}

type __premarshalInterfaceNoFragmentsQueryResponse struct {
	Root InterfaceNoFragmentsQueryRootTopic `json:"root"`

	RandomItem json.RawMessage `json:"randomItem"`

	RandomItemWithTypeName json.RawMessage `json:"randomItemWithTypeName"`

	WithPointer json.RawMessage `json:"withPointer"`
}

func (v *InterfaceNoFragmentsQueryResponse) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *InterfaceNoFragmentsQueryResponse) __premarshalJSON() (*__premarshalInterfaceNoFragmentsQueryResponse, error) {
	var retval __premarshalInterfaceNoFragmentsQueryResponse

	retval.Root = v.Root
	{

		dst := &retval.RandomItem
		src := v.RandomItem
		var err error
		*dst, err = __marshalInterfaceNoFragmentsQueryRandomItemContent(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal InterfaceNoFragmentsQueryResponse.RandomItem: %w", err)
		}
	}
	{

		dst := &retval.RandomItemWithTypeName
		src := v.RandomItemWithTypeName
		var err error
		*dst, err = __marshalInterfaceNoFragmentsQueryRandomItemWithTypeNameContent(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal InterfaceNoFragmentsQueryResponse.RandomItemWithTypeName: %w", err)
		}
	}
	{

		dst := &retval.WithPointer
		src := v.WithPointer
		if src != nil {
			var err error
			*dst, err = __marshalInterfaceNoFragmentsQueryWithPointerContent(
				src)
			if err != nil {
				return nil, fmt.Errorf(
					"unable to marshal InterfaceNoFragmentsQueryResponse.WithPointer: %w", err)
			}
		}
	}
	return &retval, nil
}

// InterfaceNoFragmentsQueryRootTopic includes the requested fields of the GraphQL type Topic.
type InterfaceNoFragmentsQueryRootTopic struct {
	// ID is documented in the Content interface.
	Id   string `json:"id"`
	Name string `json:"name"`
}

// GetId returns InterfaceNoFragmentsQueryRootTopic.Id, and is useful for accessing the field via an interface.
func (v *InterfaceNoFragmentsQueryRootTopic) GetId() string { return v.Id }

// GetName returns InterfaceNoFragmentsQueryRootTopic.Name, and is useful for accessing the field via an interface.
func (v *InterfaceNoFragmentsQueryRootTopic) GetName() string { return v.Name }

// InterfaceNoFragmentsQueryWithPointerContent includes the requested fields of the GraphQL interface Content.
//
// InterfaceNoFragmentsQueryWithPointerContent is implemented by the following types:
// InterfaceNoFragmentsQueryWithPointerContentOther
// The GraphQL type's documentation follows.
//
// Content is implemented by various types like Article, Video, and Topic.
type InterfaceNoFragmentsQueryWithPointerContent interface {
	implementsGraphQLInterfaceInterfaceNoFragmentsQueryWithPointerContent()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
	// GetId returns the interface-field "id" from its implementation.
	// The GraphQL interface field's documentation follows.
	//
	// ID is the identifier of the content.
	GetId() *string
	// GetName returns the interface-field "name" from its implementation.
	GetName() *string
}

func (v *InterfaceNoFragmentsQueryWithPointerContentOther) implementsGraphQLInterfaceInterfaceNoFragmentsQueryWithPointerContent() {
}

func __unmarshalInterfaceNoFragmentsQueryWithPointerContent(b []byte, v *InterfaceNoFragmentsQueryWithPointerContent) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "":
		return fmt.Errorf(
			"response was missing Content.__typename")
	default:
		*v = new(InterfaceNoFragmentsQueryWithPointerContentOther)
		return json.Unmarshal(b, *v)
	}
}

func __marshalInterfaceNoFragmentsQueryWithPointerContent(v *InterfaceNoFragmentsQueryWithPointerContent) ([]byte, error) {

	switch v := (*v).(type) {
	case *InterfaceNoFragmentsQueryWithPointerContentOther:
		return json.Marshal(v)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for InterfaceNoFragmentsQueryWithPointerContent: "%T"`, v)
	}
}

// InterfaceNoFragmentsQueryWithPointerContentOther is the catch-all for InterfaceNoFragmentsQueryWithPointerContent implementations that aren't explicitly fragmented; the concrete type-name is in __typename.
type InterfaceNoFragmentsQueryWithPointerContentOther struct {
	Typename string `json:"__typename"`
	// ID is the identifier of the content.
	Id   *string `json:"id"`
	Name *string `json:"name"`
}

// GetTypename returns InterfaceNoFragmentsQueryWithPointerContentOther.Typename, and is useful for accessing the field via an interface.
func (v *InterfaceNoFragmentsQueryWithPointerContentOther) GetTypename() string { return v.Typename }

// GetId returns InterfaceNoFragmentsQueryWithPointerContentOther.Id, and is useful for accessing the field via an interface.
func (v *InterfaceNoFragmentsQueryWithPointerContentOther) GetId() *string { return v.Id }

// GetName returns InterfaceNoFragmentsQueryWithPointerContentOther.Name, and is useful for accessing the field via an interface.
func (v *InterfaceNoFragmentsQueryWithPointerContentOther) GetName() *string { return v.Name }

// The query executed by InterfaceNoFragmentsQuery.
const InterfaceNoFragmentsQuery_Operation = `
query InterfaceNoFragmentsQuery {
	root {
		id
		name
	}
	randomItem {
		__typename
		id
		name
	}
	randomItemWithTypeName: randomItem {
		__typename
		id
		name
	}
	withPointer: randomItem {
		__typename
		id
		name
	}
}
`

func InterfaceNoFragmentsQuery(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *InterfaceNoFragmentsQueryResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "InterfaceNoFragmentsQuery",
		Query:  InterfaceNoFragmentsQuery_Operation,
	}

	data_ = &InterfaceNoFragmentsQueryResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

